version: 2

defaults: &defaults
  docker:
    - image: allofustest/workbench:buildimage-0.0.16
  working_directory: ~/workbench
java_defaults: &java_defaults
  <<: *defaults
  environment:
    # As best I can tell (dmohs, 7 Feb '17), this is the only way to set a memory limit that Java
    # processes executed within CircleCI's docker containers will respect. Very helpful resource:
    # https://circleci.com/blog/how-to-handle-java-oom-errors/
    #
    # In Feb 2017, this was set to 3G. But in Feb 2019 (RW-2194) we started seeing OOM errors,
    # so we bumped this down further to 2G.
    JAVA_TOOL_OPTIONS: -Xmx2g
    TERM: dumb

jobs:
  api-build-test:
    <<: *java_defaults
    steps:
      - checkout
      - run:
          command: git submodule update --init --recursive
      - run:
          #Circle is bad about setting up your remotes for you, you must use origin/
          command: |
            if [ ${CIRCLE_BRANCH} != "" ] && [ ${CIRCLE_BRANCH} != "master" ] && [ $(git diff --name-only $(git merge-base origin/master ${CIRCLE_BRANCH}) | grep api/ | wc -l | xargs) == 0 ]; then
              echo No relevant changes on non-master branch, skipping
              circleci step halt
            fi
      - restore_cache:
          keys:
          - api-cache-{{ checksum "~/workbench/api/build.gradle" }}
          - api-cache-
      - run:
          name: Validate swagger definitions
          working_directory: ~/workbench/api
          command: ./project.rb validate-swagger --project-prop verboseTestLogging=yes
      - run:
          name: Integration tests compile
          working_directory: ~/workbench/api
          command: ./project.rb gradle compileBigquerytestJava compileIntegrationJava
      - run:
          name: Unit tests
          working_directory: ~/workbench/api
          command: ./project.rb test
      - run:
          # Lint last; it's more important to surface test failures early.
          name: Java linting
          working_directory: ~/workbench/api
          command: ./gradlew spotlessCheck
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.m2
            - ~/workbench/api/build/exploded-api/WEB-INF/lib/
          key: api-cache-{{ checksum "~/workbench/api/build.gradle" }}

  api-local-test:
    docker:
      - image: allofustest/workbench:buildimage-0.0.16
      - image: mysql:5.7
        environment:
          - MYSQL_ROOT_PASSWORD=ubuntu
          - MYSQL_USER=ubuntu
          - MYSQL_PASSWORD=ubuntu
    working_directory: ~/workbench
    environment:
      # Drop to ~1.5G; the local API server starts two Java processes (the API
      # server and the cron emulator). The default machine has 4GB, so we want
      # the Java memory limit to be below half of that: other things on the
      # machine need memory as well. Using 2G here manifested in 137 errors.
      # If this limit proves to be too low, an alternative would be to use a
      # larger resource class:
      #   https://circleci.com/docs/2.0/configuration-reference/#resource_class
      JAVA_TOOL_OPTIONS: -Xmx1536m
      TERM: dumb
      MYSQL_ROOT_PASSWORD: ubuntu
    steps:
      - checkout
      - run:
          name: Fetch Submodules
          command: git submodule update --init --recursive
      - restore_cache:
          keys:
          - api-cache-{{ checksum "~/workbench/api/build.gradle" }}
          - api-cache-
      - run:
          working_directory: ~/workbench
          command: ci/activate_creds.sh api/circle-sa-key.json
      - run:
          # MySQL sometimes refuses connections by the time we attempt to apply
          # data migrations. Watch the port for 2m for startup.
          name: Await MySQL startup
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 2m
      - run:
          working_directory: ~/workbench/api
          command: ./project.rb run-local-migrations
      - run:
          working_directory: ~/workbench/api
          command: ./project.rb start-local-api && ./project.rb run-local-api-tests && ./project.rb stop-local-api
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.m2
            - ~/workbench/api/build/exploded-api/WEB-INF/lib/
          key: api-cache-{{ checksum "~/workbench/api/build.gradle" }}

  api-deploy-to-test:
    <<: *java_defaults
    steps:
      - checkout
      - run:
          command: git submodule update --init --recursive
      # Note: most of the time spent here appears to be in Gradle / App Engine
      # deployment. We tried more aggressively caching outputs via Circle
      # workspaces, but that seemed to have a negligible effect on speed. It's
      # also tricky to pick specific sub directories since the API deploy
      # touches several top level folders {common,}api.
      - restore_cache:
          keys:
          - api-cache-{{ checksum "~/workbench/api/build.gradle" }}
          - api-cache-
      - run:
          working_directory: ~/workbench
          command: ci/activate_creds.sh api/circle-sa-key.json
      - deploy:
          name: Deploy to App Engine
          working_directory: ~/workbench/api
          command: |
            ./project.rb deploy \
              --project all-of-us-workbench-test \
              --account circle-deploy-account@all-of-us-workbench-test.iam.gserviceaccount.com \
              --version circle-ci-test \
              --key-file circle-sa-key.json \
              --promote

  api-deps-check:
    <<: *java_defaults
    steps:
      - checkout
      - run:
          command: git submodule update --init --recursive
      - run:
          name: Scan dependencies for vulnerabilities
          working_directory: ~/workbench/api
          command: |
            ./project.rb gradle dependencyCheckAnalyze --info

  api-integration-test:
    <<: *java_defaults
    steps:
      - checkout
      - run:
          name: Fetch Submodules
          command: git submodule update --init --recursive
      - run:
          #Circle is bad about setting up your remotes for you, you must use origin/
          command: |
            if [ ${CIRCLE_BRANCH} != "" ] && [ ${CIRCLE_BRANCH} != "master" ] && [ $(git diff --name-only $(git merge-base origin/master ${CIRCLE_BRANCH}) | grep api/ | wc -l | xargs) == 0 ]; then
              echo No relevant changes on non-master branch, skipping
              circleci step halt
            fi
      - restore_cache:
          keys:
          - api-integration-cache-{{ checksum "~/workbench/api/build.gradle" }}
          - api-integration-cache-
      - run:
          working_directory: ~/workbench
          # Used to call gsutil from the circle environment.
          command: ci/activate_creds.sh api/circle-sa-key.json
      - run:
          working_directory: ~/workbench/api
          command: ./project.rb integration
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.m2
          key: api-integration-cache-{{ checksum "~/workbench/api/build.gradle" }}

  api-bigquery-test:
    <<: *java_defaults
    steps:
      - checkout
      - run:
          name: Fetch Submodules
          command: git submodule update --init --recursive
      - run:
          #Circle is bad about setting up your remotes for you, you must use origin/
          command: |
            if [ ${CIRCLE_BRANCH} != "" ] && [ ${CIRCLE_BRANCH} != "master" ] && [ $(git diff --name-only $(git merge-base origin/master ${CIRCLE_BRANCH}) | grep api/ | wc -l | xargs) == 0 ]; then
              echo No relevant changes on non-master branch, skipping
              circleci step halt
            fi
      - restore_cache:
          keys:
          - api-integration-cache-{{ checksum "~/workbench/api/build.gradle" }}
          - api-integration-cache-
      - run:
          working_directory: ~/workbench
          # Used to call gsutil from the circle environment.
          command: ci/activate_creds.sh api/circle-sa-key.json
      - run:
          working_directory: ~/workbench/api
          command: ./project.rb bigquerytest
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.m2
          key: api-integration-cache-{{ checksum "~/workbench/api/build.gradle" }}

  ui-build-test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Fetch Submodules
          command: git submodule update --init --recursive
      - run:
          working_directory: ~/workbench
          name: Download Swagger CLI
          command: |
            ruby -r ./aou-utils/swagger.rb -e Workbench::Swagger.download_swagger_codegen_cli
      - restore_cache:
          keys:
          - ui-cache-{{ checksum "~/workbench/ui/yarn.lock" }}
          - ui-cache-
      - run:
          working_directory: ~/workbench/ui
          command: yarn install --verbose --frozen-lockfile && yarn codegen
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: ui-cache-{{ checksum "~/workbench/ui/yarn.lock" }}
      - run:
          name: Run Angular tests
          working_directory: ~/workbench/ui
          command: |
            yarn test --no-watch --no-progress --browsers=ChromeHeadless
      - run:
          name: Run React tests (Jest)
          working_directory: ~/workbench/ui
          command: |
            yarn test-react --detectOpenHandles --forceExit --runInBand
      - run:
          name: Build with strict compilation
          working_directory: ~/workbench/ui
          command: ./project.rb build --environment test
      - run:
          # Lint last; it's more important to surface test failures early.
          name: Lint Typescript
          working_directory: ~/workbench/ui
          command: yarn run lint
      - persist_to_workspace:
          root: .
          paths:
            - ui

  # Run suite of Puppeteer end-to-end QA tests, pointed at the Workbench "test" environment.
  puppeteer-e2e-test:
    <<: *defaults
    docker:
      - image: circleci/node:13.10.1-browsers
        environment:
          NODE_ENV: development
    working_directory: ~/workbench
    parallelism: 4
    steps:
      - checkout
      - run:
          name: Fetch Submodules
          command: git submodule update --init --recursive
      - run: mkdir -p e2e/test-results
      - restore_cache:
          keys:
          - e2e-test-cache-{{ checksum "~/workbench/e2e/yarn.lock" }}
          - e2e-test-cache-
      - run: 
          working_directory: ~/workbench/e2e
          command: yarn cache clean && yarn install --verbose --frozen-lockfile
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: e2e-test-cache-{{ checksum "~/workbench/e2e/yarn.lock" }}
      - run:
          name: Update environment variables
          command: |
            echo 'export USER_NAME=$PUPPETEER_TEST_USER' >> $BASH_ENV
            echo 'export PASSWORD=$PUPPETEER_TEST_USER_PASSWORD' >> $BASH_ENV
            echo 'export INVITATION_KEY=$PUPPETEER_TEST_REGISTRATION_KEY' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Run e2e tests (Puppeteer and Jest)
          working_directory: ~/workbench/e2e
          command: |
            TESTFILES=$(circleci tests glob "test/**_test.rb" | circleci tests split --split-by=timings)
            echo ${TESTFILES}
            yarn --silent test:ci ${TESTFILES}
      - store_artifacts:
          path: e2e/logs
      - store_test_results:
          path: e2e/test-results
      
  ui-deploy-to-test:
    <<: *defaults
    steps:
      - checkout
      - run:
          command: git submodule update --init --recursive
      # Use the ui-build-test workspace here to avoid redoing the setup.
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
          - ui-cache-{{ checksum "~/workbench/ui/yarn.lock" }}
          - ui-cache-
      - deploy:
          name: Deploy to App Engine
          working_directory: ~/workbench/ui
          command: |
            ../ci/activate_creds.sh circle-sa-key.json
            ./project.rb deploy-ui \
              --project all-of-us-workbench-test \
              --account circle-deploy-account@all-of-us-workbench-test.iam.gserviceaccount.com \
              --version circle-ci-test \
              --key-file circle-sa-key.json \
              --promote

  # In staging and perf, we deploy all at once in order to track and control
  # the release for a tagged version only. In "test", we maintain individual
  # release jobs for API and UI to allow faster deploys and because we lack
  # a version tag.
  deploy-staging:
    <<: *defaults
    steps:
      - checkout
      - run:
          command: git submodule update --init --recursive
      - restore_cache:
          keys:
          - api-cache-{{ checksum "~/workbench/api/build.gradle" }}
          - api-cache-
      - deploy:
          working_directory: ~/workbench/deploy
          command: |
            ../ci/activate_creds.sh circle-sa-key.json
            ./project.rb deploy \
              --project all-of-us-rw-staging \
              --account circle-deploy-account@all-of-us-workbench-test.iam.gserviceaccount.com \
              --git-version "${CIRCLE_TAG}" \
              --app-version "${CIRCLE_TAG}" \
              --circle-url "https://circleci.com/workflow-run/${CIRCLE_WORKFLOW_ID}" \
              --key-file circle-sa-key.json \
              --promote

  deploy-perf:
    <<: *defaults
    steps:
      - checkout
      - run:
          command: git submodule update --init --recursive
      - restore_cache:
          keys:
          - api-cache-{{ checksum "~/workbench/api/build.gradle" }}
          - api-cache-
      - deploy:
          working_directory: ~/workbench/deploy
          command: |
            ../ci/activate_creds.sh circle-sa-key.json
            ./project.rb deploy \
              --project all-of-us-rw-perf \
              --account circle-deploy-account@all-of-us-workbench-test.iam.gserviceaccount.com \
              --git-version "${CIRCLE_TAG}" \
              --app-version "${CIRCLE_TAG}" \
              --circle-url "https://circleci.com/workflow-run/${CIRCLE_WORKFLOW_ID}" \
              --key-file circle-sa-key.json \
              --promote

# See https://circleci.com/docs/2.0/workflows/#git-tag-job-execution
filter_master: &filter_master
  filters:
    branches:
      only: master
filter_releases: &filter_releases
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /^v.*/

workflows:
  version: 2
  build-test-deploy:
    jobs:
      # Always run basic test/lint/compilation (open PRs, master merge).
      # Note: by default tags are not picked up.
      - api-local-test
      - api-build-test
      - ui-build-test
      - api-bigquery-test
      - api-integration-test
      - puppeteer-e2e-test

      # Run deployment to "test" on master merges.
      - api-deploy-to-test:
          <<: *filter_master
          requires:
            - api-build-test
      - ui-deploy-to-test:
          <<: *filter_master
          requires:
            - ui-build-test

  deploy-staging:
    jobs:
      - api-local-test:
          <<: *filter_releases
      - api-build-test:
          <<: *filter_releases
      - ui-build-test:
          <<: *filter_releases
      # Run slower integration tests and dep checks on release tags only.
      - api-bigquery-test:
          <<: *filter_releases
      - api-deps-check:
          <<: *filter_releases
      - api-integration-test:
          <<: *filter_releases
      - deploy-staging:
          <<: *filter_releases
          requires:
            - api-local-test
            - api-build-test
            - api-bigquery-test
            - api-deps-check
            - api-integration-test
            - ui-build-test
      - deploy-perf:
          <<: *filter_releases
          requires:
            - api-local-test
            - api-build-test
            - api-bigquery-test
            - api-deps-check
            - api-integration-test
            - ui-build-test

  integration-test:
    triggers:
      - schedule:
          # Run this command once every day at 4:00AM UTC
          cron: "0 4 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - api-integration-test
  bigquery-test:
    triggers:
      - schedule:
          # Run this command once every day at 4:00AM UTC
          cron: "0 4 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - api-bigquery-test

experimental:
  notify:
    branches:
      only:
        - master
