version: 2
jobs:
  build_and_test_and_deploy_api:
    docker:
      - image: allofustest/workbench:buildimage-0.0.4
    working_directory: ~/workbench
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
          - api-cache-{{ checksum "~/workbench/api/build.gradle" }}
          - api-cache-
      - run:
          working_directory: ~/workbench/api
          command: gradle test
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.m2
            - ~/workbench/api/build/exploded-api/WEB-INF/lib/
          key: api-cache-{{ checksum "~/workbench/api/build.gradle" }}
      - deploy:
          name: Deploy to gcloud test project
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./ci/deploy.sh api
            fi
  build_and_test_and_deploy_ui:
    docker:
      - image: allofustest/workbench:buildimage-0.0.4
    working_directory: ~/workbench
    environment: []
    steps:
      - checkout
      - run:
          working_directory: ~/
          name: Set up swagger CLI
          # This would be preferred, but would need to install ruby in the CircleCI docker image:
          # cd workbench/ui && ruby -r ./libproject/devstart.rb -e download_swagger_codegen_cli
          command: |
            cd workbench/ui && wget https://storage.googleapis.com/swagger-codegen-cli/swagger-codegen-cli-2.3.0-20170814.101630-90.jar -O libproject/swagger-codegen-cli.jar
          command: |
            cd workbench/ui && ruby -r ./libproject/devstart.rb -e download_swagger_codegen_cli
      - restore_cache:
          keys:
          - ui-cache-{{ checksum "~/workbench/ui/package.json" }}
          - ui-cache-
      - run:
          working_directory: ~/workbench/ui
          command: |
            npm install
      - save_cache:
          paths:
            - ~/workbench/ui/node_modules
          key: ui-cache-{{ checksum "~/workbench/ui/package.json" }}
      - run:
          working_directory: ~/workbench/ui
          command: |
            npm test  -- --no-watch
      - deploy:
          name: Deploy to gcloud test project
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./ci/deploy.sh ui
            fi

workflows:
  version: 2
  build_and_test_and_deploy:
    jobs:
      - build_and_test_and_deploy_api
      - build_and_test_and_deploy_ui
