version: 2
jobs:

  api-build-test-deploy:
    docker:
      - image: allofustest/workbench:buildimage-0.0.10
    working_directory: ~/workbench
    environment:
      # As best I can tell (dmohs, 7 Feb '17), this is the only way to set a memory limit that Java
      # processes executed within CircleCI's docker containers will respect. Very helpful resource:
      # https://circleci.com/blog/how-to-handle-java-oom-errors/
      # Gradle itself doesn't usually reach 1G, so as long as we can keep tasks under 3G, we should
      # have room in Circle's 4G to get our work done.
      JAVA_TOOL_OPTIONS: -Xmx3g
      TERM: dumb
    steps:
      - checkout
      - run:
          name: Fetch Submodules
          command: git submodule update --init --recursive
      - restore_cache:
          keys:
          - api-cache-{{ checksum "~/workbench/api/build.gradle" }}
          - api-cache-
      - run:
          name: Validate swagger definitions
          working_directory: ~/workbench/api
          command: ./project.rb validate-swagger --project-prop verboseTestLogging=yes
      - run:
          working_directory: ~/workbench
          command: ci/activate_creds.sh api/circle-sa-key.json
      - run:
          working_directory: ~/workbench
          command: cp api/circle-sa-key.json public-api
      - run:
          working_directory: ~/workbench/api
          command: ./project.rb test
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.m2
            - ~/workbench/api/build/exploded-api/WEB-INF/lib/
          key: api-cache-{{ checksum "~/workbench/api/build.gradle" }}
      - deploy:
          name: Deploy to gcloud test project
          working_directory: ~/workbench/api
          command: |
            ./project.rb circle-deploy \
              --project all-of-us-workbench-test --creds-file circle-sa-key.json
      - run:
          name: Scan dependencies for vulnerabilities
          working_directory: ~/workbench/api
          command: ./project.rb gradle dependencyCheckAnalyze --info
  
  api-local-tests:
    docker:
      - image: allofustest/workbench:buildimage-0.0.10
      - image: mysql:5.7
        environment:
          - MYSQL_ROOT_PASSWORD=ubuntu
          - MYSQL_USER=ubuntu
          - MYSQL_PASSWORD=ubuntu
    working_directory: ~/workbench
    environment:
      # As best I can tell (dmohs, 7 Feb '17), this is the only way to set a memory limit that Java
      # processes executed within CircleCI's docker containers will respect. Very helpful resource:
      # https://circleci.com/blog/how-to-handle-java-oom-errors/
      # Gradle itself doesn't usually reach 1G, so as long as we can keep tasks under 3G, we should
      # have room in Circle's 4G to get our work done.
      JAVA_TOOL_OPTIONS: -Xmx3g
      TERM: dumb
      MYSQL_ROOT_PASSWORD: ubuntu
    steps:
      - checkout
      - run:
          name: Fetch Submodules
          command: git submodule update --init --recursive
      - restore_cache:
          keys:
          - api-cache-{{ checksum "~/workbench/api/build.gradle" }}
          - api-cache-
      - run:
          working_directory: ~/workbench
          command: ci/activate_creds.sh api/circle-sa-key.json
      - run:
          working_directory: ~/workbench
          command: cp api/circle-sa-key.json public-api
      - run:
          # MySQL sometimes refuses connections by the time we attempt to apply
          # data migrations. Watch the port for 2m for startup.
          name: Await MySQL startup
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 2m
      - run:
          working_directory: ~/workbench/api
          command: ./project.rb run-local-migrations
      - run:
          working_directory: ~/workbench/api
          command: ./project.rb start-local-api && ./project.rb run-local-api-tests && ./project.rb stop-local-api
      - run:
          working_directory: ~/workbench/api
          command: ./project.rb start-local-public-api && ./project.rb run-local-public-api-tests && ./project.rb stop-local-public-api
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.m2
            - ~/workbench/api/build/exploded-api/WEB-INF/lib/
          key: api-cache-{{ checksum "~/workbench/api/build.gradle" }}

  api-integration-test:
    docker:
      - image: allofustest/workbench:buildimage-0.0.10
    working_directory: ~/workbench
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run:
          name: Fetch Submodules
          command: git submodule update --init --recursive
      - restore_cache:
          keys:
          - api-integration-cache-{{ checksum "~/workbench/api/build.gradle" }}
          - api-integration-cache-
      - run:
          working_directory: ~/workbench
          #Used to call gsutil from the circle environment.
          command: ci/activate_creds.sh api/circle-sa-key.json
      - run:
          working_directory: ~/workbench/api
          command: ./project.rb integration
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.m2
          key: api-integration-cache-{{ checksum "~/workbench/api/build.gradle" }}
  api-bigquery-test:
    docker:
      - image: allofustest/workbench:buildimage-0.0.10
    working_directory: ~/workbench
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run:
          name: Fetch Submodules
          command: git submodule update --init --recursive
      - restore_cache:
          keys:
          - api-integration-cache-{{ checksum "~/workbench/api/build.gradle" }}
          - api-integration-cache-
      - run:
          working_directory: ~/workbench
          #Used to call gsutil from the circle environment.
          command: ci/activate_creds.sh api/circle-sa-key.json
      - run:
          working_directory: ~/workbench/api
          command: ./project.rb bigquerytest
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.m2
          key: api-integration-cache-{{ checksum "~/workbench/api/build.gradle" }}
  ui-build-test-deploy:
    docker:
      - image: allofustest/workbench:buildimage-0.0.10
    working_directory: ~/workbench
    environment: []
    steps:
      - checkout
      - run:
          name: Fetch Submodules
          command: git submodule update --init --recursive
      - run:
          working_directory: ~/workbench
          name: Download Swagger CLI
          command: |
            ruby -r ./aou-utils/swagger.rb -e Workbench::Swagger.download_swagger_codegen_cli
      - restore_cache:
          keys:
          - ui-cache-{{ checksum "~/workbench/ui/package.json" }}
          - ui-cache-
      - run:
          working_directory: ~/workbench/ui
          command: yarn install
      - save_cache:
          paths:
            - ~/workbench/ui/node_modules
          key: ui-cache-{{ checksum "~/workbench/ui/package.json" }}
      - run:
          name: Run Angular tests
          working_directory: ~/workbench/ui
          command: |
            yarn run codegen && yarn test --no-watch --no-progress --browsers=ChromeHeadless
      - run:
          name: Test compilation of the Angular app
          working_directory: ~/workbench/ui
          command: yarn run build --no-watch --no-progress
      - deploy:
          name: Deploy to gcloud test project
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./ci/deploy_ui.sh
            else
              echo "Not master branch, skipping deploy"
            fi

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - api-build-test-deploy
      - api-local-tests
      - ui-build-test-deploy      
  integration-test:
    triggers:
      - schedule:
          # Run this command once every day at 4:00AM UTC
          cron: "0 4 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - api-integration-test
  bigquery-test:
    triggers:
      - schedule:
          # Run this command once every Sunday at 4:00AM UTC
          cron: "0 4 * * 0"
          filters:
            branches:
              only:
                - master
    jobs:
      - api-bigquery-test

experimental:
  notify:
    branches:
      only:
        - master
