version: 2
jobs:
  build_and_test_and_deploy_api:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/workbench
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
          - api-cache-{{ checksum "~/workbench/api/build.gradle" }}
          - api-cache-
      - run:
          working_directory: ~/workbench/api
          command: gradle test
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.m2
            - ~/workbench/api/build/exploded-api/WEB-INF/lib/
          key: api-cache-{{ checksum "~/workbench/api/build.gradle" }}
      - deploy:
          name: Deploy to gcloud test project
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./ci/deploy.sh api
            fi
  build_and_test_ui:
    docker:
        - image: circleci/node:latest-browsers
    working_directory: ~/workbench
    environment: []
    steps:
      - checkout
      - restore_cache:
          keys:
          - ui-cache-{{ checksum "~/workbench/ui/package.json" }}
          - ui-cache-
      - run:
          working_directory: ~/workbench/ui
          command: npm install
      - save_cache:
          paths:
            - ~/workbench/ui/node_modules
          key: ui-cache-{{ checksum "~/workbench/ui/package.json" }}
      - run:
          working_directory: ~/workbench/ui
          command: npm run test -- --no-watch
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test_and_deploy_api
      - build_and_test_ui
