version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/workbench
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
          - api-dependencies-{{ checksum "~/workbench/api/build.gradle" }}
          - api-dependencies-
      - run:
          working_directory: ~/workbench/api
          command: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.m2
          key: api-dependencies-{{ checksum "~/workbench/api/build.gradle" }}
      - run:
          working_directory: ~/workbench/api
          command: gradle test
