version: 2
jobs:
  build_and_test_and_deploy_api:
    docker:
      - image: allofustest/workbench:buildimage-0.0.9
    working_directory: ~/workbench
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run:
          name: Fetch Submodules
          command: git submodule update --init
      - restore_cache:
          keys:
          - api-cache-{{ checksum "~/workbench/api/build.gradle" }}
          - api-cache-
      - run:
          name: Validate swagger definitions
          working_directory: ~/workbench/api
          command: ./project.rb validate-swagger --project-prop verboseTestLogging=yes
      - run:
          working_directory: ~/workbench
          command: ci/activate_creds.sh api/circle-sa-key.json
      - run:
          working_directory: ~/workbench
          command: |
            gsutil cp \
              gs://all-of-us-workbench-test-credentials/all-of-us-workbench-test-9b5c623a838e.json \
              api/src/main/webapp/WEB-INF/sa-key.json
      - run:
          working_directory: ~/workbench/api
          command: gradle test --project-prop verboseTestLogging=yes
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.m2
            - ~/workbench/api/build/exploded-api/WEB-INF/lib/
          key: api-cache-{{ checksum "~/workbench/api/build.gradle" }}
      - deploy:
          name: Deploy to gcloud test project
          working_directory: ~/workbench/api
          command: |
            ./project.rb circle-deploy \
              --project all-of-us-workbench-test --creds-file circle-sa-key.json
  build_and_test_and_deploy_ui:
    docker:
      - image: allofustest/workbench:buildimage-0.0.8
    working_directory: ~/workbench
    environment: []
    steps:
      - checkout
      - run:
          name: Fetch Submodules
          command: git submodule update --init
      - run:
          working_directory: ~/workbench
          name: Download Swagger CLI
          command: |
            ruby -r ./libproject/swagger.rb -e Workbench::Swagger.download_swagger_codegen_cli
      - restore_cache:
          keys:
          - ui-cache-{{ checksum "~/workbench/ui/package.json" }}
          - ui-cache-
      - run:
          working_directory: ~/workbench/ui
          command: |
            npm install
      - save_cache:
          paths:
            - ~/workbench/ui/node_modules
          key: ui-cache-{{ checksum "~/workbench/ui/package.json" }}
      - run:
          working_directory: ~/workbench/ui
          command: |
            npm run codegen && npm test  -- --no-watch
      - deploy:
          name: Deploy to gcloud test project
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./ci/deploy_ui.sh
            fi
  test_client:
    docker:
      - image: allofustest/workbench:buildimage-0.0.8
    working_directory: ~/workbench
    environment: []
    steps:
      - checkout
      - run:
          name: Fetch Submodules
          command: git submodule update --init
      - run:
          name: Generate Swagger Python Client
          command: client/project.rb swagger-regen
      - run:
          name: Lint
          command: client/project.rb pylint
      - run:
          name: Test Python Client
          command: client/project.rb test

workflows:
  version: 2
  build_and_test_and_deploy:
    jobs:
      - build_and_test_and_deploy_api
      - build_and_test_and_deploy_ui
      - test_client

experimental:
  notify:
    branches:
      only:
        - master
