# Copied from https://github.com/broadinstitute/leonardo/blob/develop/src/main/resources/swagger/api-docs.yaml
swagger: '2.0'
info:
  title: Mailchimp
  description: |
    Workbench mail service.
  version: '0.1'


produces:
  - application/json
tags:
  - name: mail
    description: Mail API
host: https://usX.api.mailchimp.com/3.0

security:
  - googleoauth:
      - openid
      - email
      - profile

##########################################################################################
## PATHS
##########################################################################################
paths:
  'lists/{listId}/members':
    post:
      summary: Add a member
      description: Add a member to the AoU contact email list
      operationId: addMember
      tags:
        - mail
      parameters:
        - in: path
          name: listId
          type: string
          required: true
          description: Constant. Secret list Id.
        - in: body
          name: request
          schema:
            $ref: '#/definitions/ContactEmailVerificationRequest'
      responses:
        '200':
          description: User has been added to list but not verified
          schema:
            $ref: '#/definitions/EmailListAddResponse'
  'lists/{listId}/members/{userEmailHash}':
    get:
      description: Returns verification status of user's contact email
      operationId: getUserVerificationStatus
      tags:
        - mail
      parameters:
        - in: path
          name: listId
          type: string
          required: true
          description: Constant. Secret list Id.
        - in: path
          name: userEmailHash
          required: true
          type: string
      responses:
        '200':
          description: User Verification Status
          schema:
            $ref: '#/definitions/VerificationStatusResponse'



##########################################################################################
## DEFINITIONS
##########################################################################################
definitions:
  ContactEmailVerificationRequest:
    description: ''
    required:
      - status
      - contactEmail
    properties:
      status:
        type: string
      contactEmail:
        type: string
  EmailListAddResponse:
    description: ''
    required:
      - hash
    properties:
      hash:
        type: string
        description: Unique hash for each user.
  VerificationStatusResponse:
    description: ''
    required:
      - status
    properties:
      status:
        type: string
        description: The status of the user's email verification
