service: api
runtime: java11
threadsafe: true
application: "all-of-us-workbench-test"
env_variables:
  GAE_PROFILER_MODE: "cpu,heap"
  JAVA_USER_OPTS: "-Djava.util.logging.config.file=webapps/root/WEB-INF/logging.properties"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME="com.mysql.jdbc.Driver"
  SPRING_DATASOURCE_URL: "jdbc:mysql://localhost/workbench?useSSL=false"
  SPRING_DATASOURCE_USERNAME: "workbench"
  SPRING_DATASOURCE_PASSWORD: "wb-notasecret"
  CDR_DATASOURCE_URL: "jdbc:mysql://localhost/workbench?useSSL=false"
  CDR_DATASOURCE_USERNAME: "workbench"
  CDR_DATASOURCE_PASSWORD: "wb-notasecret"
error_handlers:
  - file: server_unavailable.html
handlers:
- url: /static/**
  static_dir: static
  upload: static/.*\.(js|html|sh)$
  http_headers:
    Strict-Transport-Security: "max-age=31536000; includeSubDomains; preload"
    X-XSS-Protection: "1"
    X-Content-Type-Options: "nosniff"
    Content-Security-Policy: "default-src 'none'; frame-ancestors 'none'; report-uri /content-security-report"
instance_class: "F1"
automatic_scaling:
 min_idle_instances "1"
 max_instances: "10"
inbound_services:
-warmup
