version: '3'
services:
  nginx_proxy:
    image: nginx
    ports:
      - 3000:3000
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    links:
      - ui
      - elastic
  ui:
    build:
      context: ui
    volumes:
      - ./ui:/ui
      # See https://stackoverflow.com/a/32785014 for why this is needed.
      - /ui/node_modules
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2
    ports:
      - 127.0.0.1:9200:9200
    environment:
      # Disable bootstrap checks so users don't have to fiddle with
      # vm.max_map_count. Note that this file is not used in production
      # deployments; bootstrap checks are still enabled for production
      # deployments.
      - "transport.host=localhost"
#  kibana:
#    image: docker.elastic.co/kibana/kibana-oss:6.2.2
#    logging:
#      driver: none
#    ports:
#      - 127.0.0.1:5601:5601
