runtime: python27
api_version: 1
threadsafe: true
default_expiration: "2m"

handlers:
- url: /(.*\.(css|eot|gz|html|ico|jpg|jpeg|js|map|mp4|png|svg|ttf|woff|woff2))
  static_files: dist/\1
  upload: dist/(.*)
  secure: always
  http_headers:
    Strict-Transport-Security: "max-age=31536000; includeSubDomains; preload"
    X-XSS-Protection: 1
    X-Content-Type-Options: "nosniff"
    # Reevaluate after deployment and remove "-Report-Only" if possible.
    Content-Security-Policy-Report-Only: default-src 'self'
- url: /.*
  static_files: dist/index.html
  upload: dist/index.html
  secure: always
  http_headers:
    Strict-Transport-Security: "max-age=31536000; includeSubDomains; preload"
    X-XSS-Protection: 1
    X-Content-Type-Options: "nosniff"
    # Reevaluate after deployment and remove "-Report-Only" if possible.
    Content-Security-Policy-Report-Only: default-src 'self'

# If a file (relative path under ui/) matches this regex, do not upload it.
# Skip everything not starting with "dist".
skip_files:
- ^(?!dist).*$
