runtime: python27
api_version: 1
threadsafe: true
default_expiration: "2m"

handlers:
- url: /(.*\.(css|eot|gz|html|ico|jpg|jpeg|js|map|mp4|png|svg|ttf|woff|woff2))
  static_files: dist/\1
  upload: dist/(.*)
  secure: always
  http_headers:
    Strict-Transport-Security: "max-age=31536000; includeSubDomains; preload"
    X-XSS-Protection: 1
    X-Content-Type-Options: "nosniff"
    Content-Security-Policy-Report-Only: "default-src 'none'; report-uri /content-security-report"
- url: /.*
  static_files: dist/index.html
  upload: dist/index.html
  secure: always
  http_headers:
    Strict-Transport-Security: "max-age=31536000; includeSubDomains; preload"
    X-XSS-Protection: 1
    X-Content-Type-Options: "nosniff"
    # The script-src sha-256 hash whitelists the inline Google Analytics script
    # found in index.html. If that Javascript is updated, we need to
    # simultaneously update this hash. The new hash can be computed online, e.g.
    # https://report-uri.com/home/hash or will be included in the console error
    # output if you fail to update this. Failing to update this causes Google
    # Analytics setup to fail, and may break the app entirely.
    # Note: Once we're fully on React and have finer grained control over asset
    # deployment, this inline script and hash could be removed in favor of
    # adding this to another included JS file.
    Content-Security-Policy-Report-Only: "
      default-src 'none';
      script-src
        'self'
        'sha256-WRcvuKF/fyz1ZMEquk5/ItKxTEyg/UFUSfLnSSG5Dcc='
        https://apis.google.com
        https://*.googleapis.com
        https://static.zdassets.com
        https://www.googletagmanager.com
        https://www.google-analytics.com;
      style-src
        'self'
        'unsafe-inline'
        https://fonts.googleapis.com;
      img-src
        'self'
        data:
        https://*.googleusercontent.com
        https://www.google-analytics.com;
      font-src
        'self'
        data:
        https://fonts.gstatic.com;
      connect-src
        'self'
        https://api-dot-all-of-us-workbench-test.appspot.com
        https://api-dot-all-of-us-rw-staging.appspot.com
        https://api-dot-all-of-us-rw-stable.appspot.com
        https://api.stable.fake-research-aou.org
        https://api.workbench.researchallofus.org
        https://leonardo.dsde-dev.broadinstitute.org
        https://notebooks.firecloud.org
        https://firecloud-orchestration.dsde-dev.broadinstitute.org
        https://api.firecloud.org
        https://*.googleapis.com
        https://*.zdassets.com
        https://aousupporthelp.zendesk.com
        https://www.google-analytics.com;
      child-src
        https://accounts.google.com
        https://leonardo.dsde-dev.broadinstitute.org
        https://notebooks.firecloud.org;
      report-uri /content-security-index-report"

# If a file (relative path under ui/) matches this regex, do not upload it.
# Skip everything not starting with "dist".
skip_files:
- ^(?!dist).*$
