version: "3"
services:
  ui:
    build:
      context: ./src/dev/server
    user: ${UID}
    working_dir: /w/ui
    volumes:
      - ..:/w:cached
      - ~/.config:/.config:cached
      - ~/.gsutil:/.gsutil:cached
    command: yarn start --host=0.0.0.0 ${ENV_FLAG}
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/w/ui/sa-key.json
    ports:
      - 4200:4200
  tests:
    build:
      context: ./src/dev/server
    user: ${UID}
    working_dir: /w/ui
    volumes:
      - ..:/w:cached
    command: yarn test
    ports:
      - 9876:9876
