version: "3"
services:
  db:
    image: mysql:5.7
    env_file:
      - db/vars.env
    volumes:
      - db:/var/lib/mysql
  api:
    build:
      context: ./src/dev/server
    user: ${UID}
    working_dir: /w
    volumes:
      - .:/w:cached
      - gradle-cache:/.gradle
      - ~/.config:/.config:cached
      - ~/.gsutil:/.gsutil:cached
    command: ./gradlew appengineRun
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/w/src/main/webapp/WEB-INF/sa-key.json
    env_file:
      - db/vars.env
    ports:
      - 8081:8081
      - 8001:8001
  db-migration:
    depends_on:
      - db
    build:
      context: ./src/dev/server
    user: ${UID}
    working_dir: /w/db
    volumes:
      - gradle-cache:/.gradle
      - .:/w:cached
    command: wait-for db:3306 -- ./run-migrations.sh
    env_file:
      - db/vars.env
  db-cdr-migration:
    depends_on:
      - db
    build:
      context: ./src/dev/server
    user: ${UID}
    working_dir: /w/db-cdr
    volumes:
      - gradle-cache:/.gradle
      - .:/w:cached
    command: wait-for db:3306 -- ./run-migrations.sh
    env_file:
      - db-cdr/vars.env
  update-config:
    depends_on:
      - db
    build:
     context: ./src/dev/server
    user: ${UID}
    working_dir: /w
    volumes:
      - gradle-cache:/.gradle
      - .:/w:cached
    command: wait-for db:3306 -- ./gradlew tools:loadConfig
    env_file:
      - db/vars.env
volumes:
  db:
  gradle-cache:
