version: "3"
services:
  scripts:
    build:
      context: ./src/dev/server
    user: ${UID}
    working_dir: /w/api
    volumes:
      - ..:/w:cached
      - gradle-cache:/.gradle
      - ~/.config:/.config:cached
      - ~/.gsutil:/.gsutil:cached
  db:
    image: mysql:5.7
    env_file:
      - db/vars.env
    volumes:
      - db:/var/lib/mysql
  api:
    build:
      context: ./src/dev/server
    user: ${UID}
    working_dir: /w
    volumes:
      - .:/w:cached
      - gradle-cache:/.gradle
      - ~/.config:/.config:cached
      - ~/.gsutil:/.gsutil:cached
    command: ./gradlew appengineRun
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/w/src/main/webapp/WEB-INF/sa-key.json
    env_file:
      - db/vars.env
    ports:
      - 8081:8081
      - 8001:8001
  db-migration:
    depends_on:
      - db
    build:
      context: ./src/dev/server
    user: ${UID}
    working_dir: /w/db
    volumes:
      - gradle-cache:/.gradle
      - .:/w:cached
    command: wait-for db:3306 -- ./run-migrations.sh main
    env_file:
      - db/vars.env
  db-cdr-migration:
    depends_on:
      - db
    build:
      context: ./src/dev/server
    user: ${UID}
    working_dir: /w/db-cdr
    volumes:
      - gradle-cache:/.gradle
      - .:/w:cached
    command: wait-for db:3306 -- ./run-migrations.sh schema
    env_file:
      - db-cdr/vars.env
  db-cdr-data-migration:
    depends_on:
      - db
    build:
      context: ./src/dev/server
    user: ${UID}
    working_dir: /w/db-cdr
    volumes:
      - gradle-cache:/.gradle
      - .:/w:cached
    command: wait-for db:3306 -- ./run-migrations.sh data local
    env_file:
      - db-cdr/vars.env
  db-data-migration:
    depends_on:
      - db
    build:
      context: ./src/dev/server
    user: ${UID}
    working_dir: /w/db
    volumes:
      - gradle-cache:/.gradle
      - .:/w:cached
    command: wait-for db:3306 -- ./run-migrations.sh data local
    env_file:
      - db/vars.env
  db-cdr-bigdata-migration:
      depends_on:
        - db
      build:
        context: ./src/dev/server
      user: ${UID}
      working_dir: /w/db-cdr
      volumes:
        - gradle-cache:/.gradle
        - .:/w:cached
      command: wait-for db:3306 -- ./run-bigdata-migrations.sh bigdata local
      env_file:
        - db-cdr/vars.env
  drop-cdr-db:
    depends_on:
      - db
    build:
      context: ./src/dev/server
    user: ${UID}
    working_dir: /w/db-cdr
    volumes:
      - gradle-cache:/.gradle
      - .:/w:cached
    command: wait-for db:3306 -- ./run-drop-db.sh
    env_file:
      - db-cdr/vars.env
  cloud-sql-proxy:
    build:
      context: ./src/dev/server
    user: ${UID}
    working_dir: /w
    volumes:
      - .:/w:cached
      - ~/.config:/.config:cached
      - ~/.gsutil:/.gsutil:cached
    command: |
      cloud_sql_proxy
        -instances all-of-us-workbench-test:us-central1:workbenchmaindb=tcp:0.0.0.0:3307
        -credential_file=src/main/webapp/WEB-INF/sa-key.json
  mysql-cloud:
    depends_on:
      - cloud-sql-proxy
    image: mysql:5.7
    user: ${UID}
    working_dir: /w
    volumes:
      - .:/w:cached
    entrypoint: mysql --host=cloud-sql-proxy --port=3307
  update-config:
    depends_on:
      - db
    build:
     context: ./src/dev/server
    user: ${UID}
    working_dir: /w
    volumes:
      - gradle-cache:/.gradle
      - .:/w:cached
    command: wait-for db:3306 -- ./gradlew tools:loadConfig
    env_file:
      - db/vars.env
volumes:
  db:
  gradle-cache:
