version: "3.4"
x-api-defaults: &api-defaults
  build:
    context: ./src/dev/server
  image: allofustest/workbench-dev-api:local
  user: ${UID}
  working_dir: /w/api
  environment:
    - GOOGLE_APPLICATION_CREDENTIALS=/w/api/sa-key.json
  env_file:
    - db/vars.env
  volumes:
    - src-sync:/w:nocopy
    - gradle-cache:/.gradle
    - ~/.config:/.config:cached
    - ~/.gsutil:/.gsutil:cached
services:
  scripts:
    <<: *api-defaults
  db:
    image: mysql:5.7.27
    env_file:
      - db/vars.env
    volumes:
      - db:/var/lib/mysql
    ports:
      - 127.0.0.1:3306:3306
  api:
    <<: *api-defaults
    depends_on:
      - db
    command: ./project.rb start-api-and-incremental-build
    ports:
      - 127.0.0.1:8081:8081
      - 127.0.0.1:8001:8001
  es-scripts:
    <<: *api-defaults
  db-scripts:
    <<: *api-defaults
    depends_on:
      - db
    working_dir: /w/api/db
    entrypoint: ['with-uid.sh', 'wait-for-it', 'db:3306', '-t', '30', --]

  api-scripts:
    <<: *api-defaults
    depends_on:
      - db
    entrypoint: ['with-uid.sh', 'wait-for-it', 'db:3306', '-t', '30', --]

  cdr-scripts:
    <<: *api-defaults
    depends_on:
      - db
    working_dir: /w/api/db-cdr
    entrypoint: ['with-uid.sh', 'wait-for-it', 'db:3306', '-t', '30', --]
    env_file: db-cdr/vars.env

  db-make-bq-tables:
    <<: *api-defaults
    depends_on:
      - db
    working_dir: /w/db-cdr
    env_file: db-cdr/vars.env

  db-cloudsql-import:
    <<: *api-defaults
    working_dir: /w/db-cdr
    entrypoint: ["./generate-cdr/cloudsql-import.sh"]

  db-local-mysql-import:
    <<: *api-defaults
    working_dir: /w/db-cdr
    entrypoint: ["./generate-cdr/local-mysql-import.sh"]

volumes:
  db:
  esdata:
  gradle-cache:
  src-sync:
    external: true

