version: "3"
services:
  db:
    image: mysql:5.7
    env_file:
      - db/vars.env
    volumes:
      - db:/var/lib/mysql
  api:
    build:
      context: ./src/dev/server
    user: ${UID}
    working_dir: /w
    depends_on:
      - db
    volumes:
      - .:/w:cached
      - gradle-cache:/.gradle
    command: ./gradlew appengineRun
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/w/sa-key.json
    env_file:
      - db/vars.env
    ports:
      - 8081:8081
      - 8001:8001
volumes:
  db:
  gradle-cache:
